title: The Religion Humanity Initiative
description: m

url: http://brianmaierjr.github.com/long-haul
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: redcarpet
highlighter: pygments
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Contact
   url: /contact

social:
   github: rh-initiative
   twitter: m
   facebook: pages/The-Religion-Humanity-Initiative/1555114474755581
   email: brimaidesigns@gmail.com

google_analytics: "UA-58263416-1"
